travis:
  secure:
    BINSTAR_TOKEN: RiOiZAcscVCKJWdJF+GyxhNTTzzW3eQr0t9M7rMxdo2GlVcRkrs9mR9DfkYRMA6XSZicBQl2eMwworB7ggmj9d5Tu4sKlIFlR1ePm72lIoxBidE8AoLoqatvQFyAA4yd9bWB8FvE4zkh8qb6OTCtQJF28HGpCGbziRzj7YfsM/D4O9axgNd3pQl4PZrFh76T6f619+/9h6XlVDIMrlr+BqGFP4qBIYocfZ0soJnN5EBNNtX51Uca67FD3/+eLRc9yjq1P1eOyZP2mkWTPGgwTC/L0isGBYo+c2mbsS9b1OgarpmIq6BijqRyDB6T5InwaCum1YvvEWHfeOSR+gggDWIOAtSd/VYtuU4TD2wLMwyBpOvzLAKaAc9AXDADli1igFIp7G9tb/n7kPtgvcYWx2h8viSMVsvjjL61bxMzvOCME6Poqu3bytna4AZROGk1Lb5MtuD1cZBxzUPuWF/jKZBmCYGSNth5OxTPFpwcDaJoG9nM8K+6B/6UV734kXUc1Huhj9mQNHOYAF6sq6GMcKuYQ80CqNi2qmX7WO5pOPrIaf5H+kYw1TlTt+Fz/blpM5IigWQtfObftYur6gj/BPJUHBowNDBYtKJjvw+pJ0wxtyB7LAhzkjy3wPBGw+y1gdFqUYEw9yFSaTS1o3PYF4MHMjqu0OPhupBb+jALbHo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
